spring:
  activemq:
    # activemq url
    broker-url: tcp://139.159.217.217:61617
    in-memory: true
    pool:
      # 如果此处设置为true，需要添加activemq-pool的依赖包，否则会自动配置失败，无法注入JmsMessagingTemplate
      enabled: false
    user: admin
    password: admin
server:
  port: 8081
